language: python
python:
  - "2.7"
# prepare xvfb for Selenium testing
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
# command to install dependencies
install: "pip install -r requirements.txt"
# cd into directory with manage.py module
before_script:
  - cd mod_drops
# command to run tests
script:
  - coverage run --source=mod_drop,user_profile manage.py test
# command to run Coveralls
# after_success:
#   - coveralls