language: python
services:
  - postgresql
env:
  test:
  - DATABASE_URL='postgres://postgres:@localhost:5432/test'
  - DJANGO_CONFIGURATION=Dev 
  - DJANGO_SETTINGS_MODULE=mod_drops.settings
python:
  - "2.7"
addons:
  postgresql: "9.3"
# prepare xvfb for Selenium testing
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
# command to install dependencies
install: "pip install -r requirements.txt"
# cd into directory with manage.py module
before_script:
  - cd ./
  - psql -c 'create database test;' -U postgres
  - python manage.py migrate --noinput
  - python manage.py collectstatic --noinput
# command to run tests
script:
  - python manage.py test
#  - coverage run --source=mod_drop,user_profile manage.py test
# command to run Coveralls
# after_success:
#   - coveralls