---

- name: Install Requirements
  sudo: yes
  pip: name=gunicorn state=present

- name: Get Host Email Password
  include_vars: secrets.yml

- name: Set Host Password
  set_fact: 
    host_password: "{{ email_password }}"

- name: Create gunicorn Upstart Job
  sudo: yes
  template: src=imager.conf.j2 dest=/etc/init/imager.conf

- name: Start gunicorn Upstart Job
  sudo: yes
  service: name=imager state=restarted
